name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to the `spoonriver-web` repository! If you haven't already, please review our [Contribution Guidelines](CONTRIBUTING.md)"
          pr-message: "Welcome to the `spoonriver-web` repository and thanks for your interest in helping to improve this resource! If you haven't already, please review our [Contribution Guidelines](CONTRIBUTING.md)"
